# Generated by Django 4.2.6 on 2024-01-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp1', '0004_coursepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='random_text',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
