# Generated by Django 4.2.6 on 2024-01-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp1', '0006_rename_random_text_coursepage_about_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='about_course',
            field=models.CharField(max_length=600),
        ),
    ]
