# Generated by Django 4.2.6 on 2024-01-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp1', '0008_pdfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfs',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userapp1.coursepage'),
            preserve_default=False,
        ),
    ]
