# Generated by Django 4.2.6 on 2024-01-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp1', '0009_pdfs_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pdfs',
            new_name='pdf',
        ),
    ]
