# Generated by Django 4.2.6 on 2024-01-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp1', '0010_rename_pdfs_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=80)),
                ('video_description', models.CharField(max_length=150)),
                ('video_content', models.FileField(upload_to='video/%y')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp1.coursepage')),
            ],
        ),
    ]
