# Generated by Django 4.2.6 on 2024-01-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp1', '0012_videolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolink',
            name='video_link',
            field=models.URLField(),
        ),
    ]
